### ISSUE TITLE
Inaccessible host: `session.qldb.frankfurt.amazonaws.com'. 

### ISSUE THREAD

**Issue by florianlenz** [awslabs/amazon-qldb-driver-nodejs#6]
Hi. I am running into the following issue:

```js
{ UnknownEndpoint: Inaccessible host: `session.qldb.frankfurt.amazonaws.com'. This service may not be available in the `frankfurt' region.
    at Request.ENOTFOUND_ERROR (/Users/florian/projects/qldb/node_modules/aws-sdk/lib/event_listeners.js:495:46)
    at Request.callListeners (/Users/florian/projects/qldb/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/florian/projects/qldb/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/florian/projects/qldb/node_modules/aws-sdk/lib/request.js:683:14)
    at ClientRequest.error (/Users/florian/projects/qldb/node_modules/aws-sdk/lib/event_listeners.js:333:22)
    at ClientRequest.<anonymous> (/Users/florian/projects/qldb/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
  message:
   'Inaccessible host: `session.qldb.frankfurt.amazonaws.com\'. This service may not be available in the `frankfurt\' region.',
  code: 'UnknownEndpoint',
  region: 'frankfurt',
  hostname: 'session.qldb.frankfurt.amazonaws.com',
  retryable: true,
  originalError:
   { Error: getaddrinfo ENOTFOUND session.qldb.frankfurt.amazonaws.com session.qldb.frankfurt.amazonaws.com:443
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
     message:
      'getaddrinfo ENOTFOUND session.qldb.frankfurt.amazonaws.com session.qldb.frankfurt.amazonaws.com:443',
     errno: 'ENOTFOUND',
     code: 'NetworkingError',
     syscall: 'getaddrinfo',
     hostname: 'session.qldb.frankfurt.amazonaws.com',
     host: 'session.qldb.frankfurt.amazonaws.com',
     port: 443,
     region: 'frankfurt',
     retryable: true,
     time: 2019-11-25T16:12:56.537Z },
  time: 2019-11-25T16:12:56.538Z }
```

This is my code:
```typescript
import {PooledQldbDriver} from "amazon-qldb-driver-nodejs"

const driver = new PooledQldbDriver(
    "my-ledger",
    {
        region: "frankfurt"
    },
    0,
    500,
    3000,
);

driver
    .getSession()
    .then(session => {
        console.log("received session");
    })
    .catch(console.error);
```

I specified my access material via the `AWS_ACCESS_KEY_ID` and the `AWS_SECRET_ACCESS_KEY` env variable. 

I am not sure what's causing the error. Let me know if I can help to debug somehow.

**Comment by siddsanyal** [comment]
Hi Florian,

You need to specify the AWS region in Frankfurt using the region code "eu-central-1".
For future reference, please see this list of service endpoints you can use in your configurations https://docs.aws.amazon.com/general/latest/gr/rande.html#qldb_region .

Thanks

**Comment by florianlenz** [comment]
Thank you for the explanation and the docs.
